language: go
# see https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
# for the detail
# sudo: requried
dist: trusty
env:
  global:
    - REGISTRY_USER=nfvperobot
    - secure: "X5/hQysr/F9tT9N9gYN/2LQvGJMzfRucTCx/fD6lB5KZIPNJSd/NDIR0TX8YmcQkAxNN4yQ1HrmlNHzjzq8si6dxWCYOY2/4Rm1mB2gK0/sNf/HL9V8zdCdGPGJON3u+WE3bC/VMMN31cobR6npHUIZAtAkd73HIDtmjgTv3gHw4ts3dm4cwQOMF8HHRTEYaVWM9NfAm6DC2mR0iyLQq+wdifTXjPwxTb3b2jat3UvSBHILDB+WVifp4giQ3NKfckerY7RLklskzD+upfL001N6KK12OiMEP9ppXX8oSly53PYTOUYcCEM1rXygxYQclUgZC6knLt5s5ztPO8y4/vU4EUvG8egyipc2f1tBf5RD1Q9VwxOZqFtSZq8L/be7U5TdkFg7zNzRfbaQ099YIa2il4r3w4PnQWGihewoR+7yiKkMqsnz7PpTLne2Y6D9q+jGCzWpRALJ6x4ArAnxEr896dy9qDTP7aDVNOYPm627G41czjqFenI9wPrEG1INVQeT+stQhtQo8eL+S8p93Gn8I8NkYPP6jyveVL37xYcGTIoEWivxmf+Lox0FZhwiKzewh0OS/TiIYyv4BIPSuXHqu27x84SjLJ6kay9QvrqX6qNgnoyXMOAb6Y7qDITG/BBpHsASF4ertcS4QhIr1xA6U8dwoddGJWAqkVs5YavA="

before_install:
  - sudo apt-get update -qq

install:
  - go get github.com/golang/lint/golint

before_script:
  - golint .
  - go fmt .
  - go vet .
  # was failing with: `gocyclo: vendor/golang.org/x/net/context/go19.go:15:14: expected type, found '=' (and 1 more errors)`
  # - gocyclo -over 15 .

script:
  - go build -o k8s-dummy-device-plugin

# These are kind of better than "after_success" as they can be more conditional
# e.g. when merging into master.
# before_deploy:
# deploy:
#   provider: script
#   script: docker push nfvpe/dummy-dp
#   on:
#     branch: master

# Using this for now so it triggers every time other tests succeed.
after_success:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker build -t nfvpe/dummy-device-plugin .
  - docker push nfvpe/dummy-device-plugin